/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupon;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.text.Normalizer.Form;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.text.Position;

/**
 *
 * @author OM SHUBHAM
 */
public class GroupChatPage extends javax.swing.JFrame {

    /**
     * Creates new form GroupChatPage
     */
    public GroupChatPage() {
        initComponents();
    }
    
   
      String port = null;
    String ipaddress = null;
    Socket soc;
    DataInputStream din = null;
    DataOutputStream dout = null;
    String LoginName;
    String addto = "";
    String sendto="";
    String removeTo="";

    public GroupChatPage(String IPaddress, String Port, String login_name) throws IOException {
          initComponents();
        ChatHistory.setEditable(false);
        this.setTitle(login_name + " : Online");
        AvailableUser.clear();
        port = Port;
        msgBox.setText(null);
        ipaddress = IPaddress;
        LoginName = login_name;
        soc = new Socket(ipaddress, Integer.parseInt(port));
        din = new DataInputStream(soc.getInputStream());
        dout = new DataOutputStream(soc.getOutputStream());
        dout.writeUTF(LoginName);
        ClientRead cr = new ClientRead(soc);
        
    }
    
    class ClientRead extends Thread{
        
          Socket sock=null;
          DataInputStream dinp=null;
    
        ClientRead(Socket csoc) throws IOException{
           
            sock = csoc;
            start();
        }
        
       public void run(){
        
           while (true) {
            try {
                dinp=new DataInputStream(sock.getInputStream());
                String msg = dinp.readUTF();
                String realMsg = "";
                StringTokenizer st = new StringTokenizer(msg);
                String from = st.nextToken();
       
                if (from.equals("#REFRESH#")) {

                AvailableUser.clear();

                    
                    while(st.hasMoreTokens())
                        AvailableUser.add(st.nextToken());
                }
                else if(from.equals("#ERROR#")){
                  ChatHistory.append("--->" + "cannot send-------------USER offline !");  
                }
                    
                else {
                    while (st.hasMoreTokens()) {
                        realMsg = realMsg + " " + st.nextToken();
                    }

                    ChatHistory.append("\n" + from + ": " + realMsg);
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

    }
           
        }
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ChatHistory = new javax.swing.JTextArea();
        AvailableUser = new java.awt.List();
        send = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        addToGroup = new javax.swing.JButton();
        curGroup = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        removeFromGroup = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ChatHistory.setEditable(false);
        ChatHistory.setColumns(20);
        ChatHistory.setRows(5);
        jScrollPane2.setViewportView(ChatHistory);

        AvailableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AvailableUserMouseClicked(evt);
            }
        });

        send.setBackground(new java.awt.Color(0, 153, 0));
        send.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        send.setText("SEND");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(0, 0, 255));
        refresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 0, 51));
        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        addToGroup.setBackground(new java.awt.Color(0, 153, 0));
        addToGroup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addToGroup.setText("Add To Group");
        addToGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToGroupActionPerformed(evt);
            }
        });

        curGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                curGroupMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("        Your Group :");

        removeFromGroup.setBackground(new java.awt.Color(255, 51, 51));
        removeFromGroup.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        removeFromGroup.setText("Remove from Group");
        removeFromGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromGroupActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Online :");

        msgBox.setColumns(20);
        msgBox.setRows(5);
        jScrollPane1.setViewportView(msgBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(curGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeFromGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addToGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AvailableUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(AvailableUser, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addToGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refresh))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(curGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeFromGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(send, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       
        try {
            dout.writeUTF(LoginName + " " + LoginName + " " + "#LOGOUT#");
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();  

      // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
         
      try {
            dout.writeUTF(LoginName+ " " + LoginName + " " + "#REFRESH#");
       
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
      
       if(msgBox.getText().length() > 0){
        sendto ="#GROUP# "+LoginName+ " #GROUP#";
        for(int i=0;i < curGroup.getItemCount();i++){
           String x = curGroup.getItem(i);
           sendto = sendto+" " + x ;
       }
        try {
            dout.writeUTF(sendto);
            dout.writeUTF(msgBox.getText());
        } catch (IOException ex) {
            Logger.getLogger(GroupChatPage.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
        
    }//GEN-LAST:event_sendActionPerformed

    private void addToGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToGroupActionPerformed
        
       int flag=0;

       for(int i=0;i < curGroup.getItemCount();i++){
           String x = curGroup.getItem(i);
           if(x.equals(addto))
               flag=1;
       }
       
       if(flag==0){
           curGroup.add(addto);
       }
       else {
           JOptionPane.showMessageDialog(null,"Already in Group");
       }
           
       // TODO add your handling code here:
    }//GEN-LAST:event_addToGroupActionPerformed

    private void AvailableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AvailableUserMouseClicked
        
      String x[]=AvailableUser.getSelectedItems();
      addto = x[0];
      // TODO add your handling code here:
    }//GEN-LAST:event_AvailableUserMouseClicked

    private void removeFromGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromGroupActionPerformed
        
     for(int i=0;i < curGroup.getItemCount();i++){
           String x = curGroup.getItem(i);
           if(x.equals(removeTo))
               curGroup.remove(x);
       }
    // TODO add your handling code here:
    }//GEN-LAST:event_removeFromGroupActionPerformed

    private void curGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curGroupMouseClicked
        
       String x[]=curGroup.getSelectedItems();
      removeTo = x[0];
       // TODO add your handling code here:
    }//GEN-LAST:event_curGroupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupChatPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupChatPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupChatPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupChatPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupChatPage().setVisible(true);
            }
        });
    }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List AvailableUser;
    private javax.swing.JTextArea ChatHistory;
    private javax.swing.JButton addToGroup;
    private java.awt.List curGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logout;
    private javax.swing.JTextArea msgBox;
    private javax.swing.JButton refresh;
    private javax.swing.JButton removeFromGroup;
    private javax.swing.JButton send;
    // End of variables declaration//GEN-END:variables
}
