/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupon;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author OM SHUBHAM
 */
public class LoginPage1 extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form LoginPage1
     */
    public LoginPage1() {
        initComponents();
    }

    String mn=null;
    public String getusername() {
        mn=username.getText();
        return mn;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        forgetpwd = new javax.swing.JButton();
        pwd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 204, 0));
        setLocation(new java.awt.Point(450, 200));
        setPreferredSize(new java.awt.Dimension(320, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 190, 90, 14);
        getContentPane().add(username);
        username.setBounds(50, 210, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 240, 90, 14);

        login.setBackground(new java.awt.Color(0, 204, 204));
        login.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(70, 300, 70, 23);

        signup.setBackground(new java.awt.Color(0, 204, 204));
        signup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signup.setText("SignUp");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(155, 300, 80, 23);

        forgetpwd.setBackground(new java.awt.Color(0, 204, 204));
        forgetpwd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        forgetpwd.setForeground(new java.awt.Color(204, 0, 0));
        forgetpwd.setText("Forget Password");
        getContentPane().add(forgetpwd);
        forgetpwd.setBounds(73, 340, 160, 23);
        getContentPane().add(pwd);
        pwd.setBounds(50, 260, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupon/logo3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 220, 160);

        jLabel3.setBackground(new java.awt.Color(51, 255, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupon/backg.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 320, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        RegisterPage rgpage= new RegisterPage();
        dispose();
        rgpage.setVisible(true);
    }//GEN-LAST:event_signupActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        conn=MysqlConnect.ConnectDB();
        String sql="select * from login_info where username=? and password=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,username.getText());
            pst.setString(2,pwd.getText());
            rs=pst.executeQuery();
            if(rs.next()) {
                JOptionPane.showMessageDialog(null,"You are succesfully LogedIn");
                dispose();
                String u=username.getText();
                String pd=pwd.getText();
                //Profile pp=new Profile(u);
                //pp.start();
                NewFrontPage mpage =new NewFrontPage(u,pd);
                mpage.setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "invalid details","Access denied",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forgetpwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton signup;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
