/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupon;

/**
 *
 * @author OM SHUBHAM
 */
public class NewFrontPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewFrontPage() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255,255,255));
    }
    String sur=null,pwd;
    public NewFrontPage(String su,String pd) {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255,255,255));
        this.setTitle("Username : "+ sur);
        sur=su;
        pwd=pd;
        frontpage_username.setText(su);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        popupMenu3 = new java.awt.PopupMenu();
        popupMenu4 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        fr_privateChat = new javax.swing.JLabel();
        fr_grpChat = new javax.swing.JLabel();
        fr_myprofile = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        frontpage_username = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        popupMenu3.setLabel("popupMenu3");

        popupMenu4.setLabel("popupMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GroupOn");
        setPreferredSize(new java.awt.Dimension(569, 520));
        setResizable(false);
        setSize(new java.awt.Dimension(569, 501));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupon/logo.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 227, 165);

        fr_privateChat.setBackground(new java.awt.Color(153, 204, 0));
        fr_privateChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupon/chaticongrp.png"))); // NOI18N
        fr_privateChat.setText("jLabel2");
        fr_privateChat.setOpaque(true);
        fr_privateChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fr_privateChatMouseClicked(evt);
            }
        });
        getContentPane().add(fr_privateChat);
        fr_privateChat.setBounds(50, 340, 110, 120);

        fr_grpChat.setBackground(new java.awt.Color(255, 255, 255));
        fr_grpChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupon/GroupIcon.png"))); // NOI18N
        fr_grpChat.setText("jLabel2");
        fr_grpChat.setOpaque(true);
        fr_grpChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fr_grpChatMouseClicked(evt);
            }
        });
        getContentPane().add(fr_grpChat);
        fr_grpChat.setBounds(390, 340, 120, 120);

        fr_myprofile.setBackground(new java.awt.Color(0, 153, 102));
        fr_myprofile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fr_myprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupon/profilegrp.png"))); // NOI18N
        fr_myprofile.setText("jLabel2");
        fr_myprofile.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fr_myprofile.setOpaque(true);
        fr_myprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fr_myprofileMouseClicked(evt);
            }
        });
        getContentPane().add(fr_myprofile);
        fr_myprofile.setBounds(230, 232, 110, 120);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Group Chat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 460, 120, 30);

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("My Profile");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 350, 110, 30);

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Private Chat");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 460, 110, 30);

        frontpage_username.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        frontpage_username.setForeground(new java.awt.Color(0, 102, 102));
        frontpage_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frontpage_username.setText("Username");
        getContentPane().add(frontpage_username);
        frontpage_username.setBounds(130, 170, 310, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fr_privateChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fr_privateChatMouseClicked
        // TODO add your handling code here:
        ConnectionINFO ci = new ConnectionINFO(sur,1);
        ci.setVisible(true);
    }//GEN-LAST:event_fr_privateChatMouseClicked

    private void fr_myprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fr_myprofileMouseClicked
        // TODO add your handling code here:
//        Profile pf=new Profile();
//        pf.start();
     
        Profile pp= new Profile(sur,pwd);
        pp.setVisible(true);
    }//GEN-LAST:event_fr_myprofileMouseClicked

    private void fr_grpChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fr_grpChatMouseClicked
       
       ConnectionINFO ci = new ConnectionINFO(sur,2);
        ci.setVisible(true); 
       // TODO add your handling code here:
    }//GEN-LAST:event_fr_grpChatMouseClicked

    public void start() {
        LoginPage1 lp= new LoginPage1();
        String ss=lp.getusername();
        frontpage_username.setText(ss);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        NewFrontPage nm=new NewFrontPage();
        nm.start();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFrontPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fr_grpChat;
    private javax.swing.JLabel fr_myprofile;
    private javax.swing.JLabel fr_privateChat;
    private javax.swing.JLabel frontpage_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private java.awt.PopupMenu popupMenu3;
    private java.awt.PopupMenu popupMenu4;
    // End of variables declaration//GEN-END:variables
}
